version: "3"
services:
    node:
        image: node:10-alpine
        working_dir: /home/node/app
        command: npm install && npm start
        ports:
            - 3000:3000
        volumes:
            - .:/home/node/app